### ISSUE TITLE
Can't setup gopy to work

### ISSUE THREAD

**Issue by robooo** [go-python/gopy#203] opened 2019-10-29 13:26 UTC
I can't get gopy works even with python console, bash or docker. Tried all examples from README

go version go1.13.1 linux/amd64
ubuntu 16.04
Python 3.6.8

1. gopy build + console
```
$ python
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import hi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kistler/go-sdk/out/hi.py", line 15, in <module>
    import _hi
ImportError: hi_go.so: cannot open shared object file: No such file or directory
>>> 
```

2. python console
```
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gopy
>>> gopy.load()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'gopy' has no attribute 'load'
>>> 
```

3. docker
```
docker build --network=host -t go-python/gopy .
Sending build context to Docker daemon  4.836MB
Step 1/3 : FROM golang:onbuild
# Executing 3 build triggers
 ---> Using cache
 ---> Running in 921b4192dcac
+ exec go get -v -d
github.com/go-python/gopy (download)
github.com/pkg/errors (download)
github.com/gonuts/commander (download)
github.com/gonuts/flag (download)
Fetching https://golang.org/x/tools/go/packages?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/packages?go-get=1 (status code 200)
get "golang.org/x/tools/go/packages": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/packages?go-get=1
get "golang.org/x/tools/go/packages": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools?go-get=1
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
golang.org/x/tools (download)
Removing intermediate container 921b4192dcac
 ---> Running in 1cac7d2530d9
+ exec go install -v
github.com/pkg/errors
golang.org/x/tools/go/internal/gcimporter
github.com/gonuts/flag
golang.org/x/tools/go/internal/packagesdriver
golang.org/x/tools/internal/fastwalk
golang.org/x/tools/internal/semver
golang.org/x/tools/internal/span
golang.org/x/tools/internal/gopathwalk
# golang.org/x/tools/go/internal/packagesdriver
../golang.org/x/tools/go/internal/packagesdriver/sizes.go:107: undefined: types.SizesFor
github.com/go-python/gopy/bind
# golang.org/x/tools/go/internal/gcimporter
../golang.org/x/tools/go/internal/gcimporter/bexport.go:212: obj.IsAlias undefined (type *types.TypeName has no field or method IsAlias)
../golang.org/x/tools/go/internal/gcimporter/iexport.go:234: obj.IsAlias undefined (type *types.TypeName has no field or method IsAlias)
github.com/gonuts/commander
# github.com/go-python/gopy/bind
../github.com/go-python/gopy/bind/symbols.go:134: f.Embedded undefined (type *types.Var has no field or method Embedded)
../github.com/go-python/gopy/bind/symbols.go:1001: f.Embedded undefined (type *types.Var has no field or method Embedded)
../github.com/go-python/gopy/bind/types.go:133: f.Embedded undefined (type *types.Var has no field or method Embedded)
The command '/bin/sh -c go-wrapper install' returned a non-zero code: 2
```

I will appreciate any help!

**Comment by HuiiBuh** [comment] 2019-11-14 14:01
I have the exact same problem as you describe. I am on Linux Mint 19.2 and have go version go1.13.4 linux/amd64 installed

**Comment by acm0055** [comment] 2019-11-25 07:19
@robooo @HuiiBuh  I am unsure of the exact reason, but I was helping a friend with a similar issue as in 1. For him, it was something with the LD path. Maybe it could be an issue with not looking locally or some python configuration issue. I am unsure.

The following should be a hack to make it work. Try this and see if it helps.

```
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD python
```

**Comment by m20082008m** [comment] 2020-01-07 12:14
I have same problem as you, but if you pip install your project, this can not solve my problem. I add  -Wl,-rpath=\$ORIGIN to gcc such that readelf -d _hi.so | grep RUNPATH shows (RUNPATH) Library runpath: [$ORIGIN]. 
I get this method from https://stackoverflow.com/questions/856116/changing-ld-library-path-at-runtime-for-ctypes

**Comment by m20082008m** [comment] 2020-01-07 12:18
`gopy build -output=out ./hi

--- Processing package: github.com/go-python/gopy/_examples/hi ---

--- building package ---
gopy build -output=out ./hi
goimports -w hi.go
go build -buildmode=c-shared -o hi_go.so .
python build.py
go env CC
python-config --cflags
python-config --ldflags
gcc hi.c hi_go.so -o _hi.so ...`

`gcc hi.c hi_go.so -o _hi.so ...  -Wl,-rpath=$ORIGIN`

**Comment by kushaldas** [comment] 2020-04-14 05:19
I can also reproduce this issue.

**Comment by sbinet** [comment] 2020-04-14 08:59
@rcoreilly ?

**Comment by acm0055** [comment] 2020-04-14 17:31
Its been a while since I have worked on this (i.e. a semester ago), it might be helpful looking into how certain library loading schemes handles local loading. I remember at some point having an issue with loading locally not working with (./library) style based on some (I think) LD_CONFIG settings. However, I cannot confirm this as of now

**Comment by kushaldas** [comment] 2020-04-16 07:35
I am also trying to figure out how the tests are running and passing in the CI. Tried this (on both Debian Buster + Python3.7 and Ubuntu Xenial + Python3.5). 


```
root@17a6aa2bb974:~/gocode/src/github.com/kushaldas/garam# gopy build -output=/tmp/output -vm=/usr/bin/python3 github.com/kushaldas/garam/pkg/madeingo

--- Processing package: github.com/kushaldas/garam/pkg/madeingo ---

--- building package ---
gopy build -output=/tmp/output -vm=/usr/bin/python3 github.com/kushaldas/garam/pkg/madeingo
goimports -w madeingo.go
go build -buildmode=c-shared -o madeingo_go.so .
/usr/bin/python3 build.py
go run patch-leaks.go madeingo.c # patch memory leaks in pybindgen output
go env CC
/usr/bin/python3-config --cflags
/usr/bin/python3-config --ldflags
gcc madeingo.c madeingo_go.so -o _madeingo.so -I/usr/include/python3.5m -I/usr/include/python3.5m -Wno-unused-result -Wsign-compare -g -fstack-protector-strong -Wformat -Werror=format-security -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -L/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu -L/usr/lib -lpython3.5m -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions -fPIC --shared -Ofast
root@17a6aa2bb974:~/gocode/src/github.com/kushaldas/garam# cd /tmp/output/
root@17a6aa2bb974:/tmp/output# ls
Makefile  __init__.py  _madeingo.so  build.py  go.py  madeingo.c  madeingo.go  madeingo.py  madeingo_go.h  madeingo_go.so  patch-leaks.go
root@17a6aa2bb974:/tmp/output# python3
Python 3.5.2 (default, Oct  8 2019, 13:06:37) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import madeingo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/output/madeingo.py", line 12, in <module>
    import _madeingo
ImportError: madeingo_go.so: cannot open shared object file: No such file or directory
>>> 
root@17a6aa2bb974:/tmp/output# ldd _madeingo.so 
	linux-vdso.so.1 =>  (0x00007ffc4306a000)
	madeingo_go.so => not found
	libpython3.5m.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0 (0x00007f7daad9e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7daa9d4000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7daa7b7000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f7daa58e000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f7daa374000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f7daa170000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f7da9f6d000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f7da9c64000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7dab631000)

```

If I just copy the `madeingo_go.so` or `hi_go.so` in our main example to the right path (`/usr/lib`), the system can find the right shared library file. But, otherwise it can not. Any help on this will be really helpful.

**Comment by kushaldas** [comment] 2020-04-19 07:50
@rcoreilly @sbinet When you have time, please have a look at this issue.

**Comment by songololo** [comment] 2020-05-22 09:53
Another hopeful request to please see if this can be resolved. Thanks!

**Comment by rcoreilly** [comment] 2020-05-22 10:04
Sorry for not being able to look at this -- from what I can tell, the underlying issue is the linker not being able to find the .so files.  This has to be solved by adding the proper path to LD_LIBRARY_PATH at some level, and by finding exactly where the .so files are, this should be solvable, at least at a workaround level.

I will try to boot up my linux system at some point soon and see if I can provide some further insight.  I haven't really run gopy on anything other than my mac at this point.. Sorry very busy this quarter.

**Comment by songololo** [comment] 2020-09-09 16:07
Just bumping this thread in the hopes that this item could possibly be resolved? Would love to give this package a try.

**Comment by acm0055** [comment] 2020-09-09 16:18
@songololo Did you try my workaround in https://github.com/go-python/gopy/issues/203#issuecomment-558024577

**Comment by rcoreilly** [comment] 2020-09-19 01:07
I finally had a chance to get my linux setup running again and I wasn't able to reproduce.  also the test case above github.com/kushaldas/garam doesn't seem to be present anymore.

As I noted above, this looks like a generic LD_LIBRARY_PATH issue that just needs the proper path(s) to be added, and thus may have nothing to do with this tool per se.  for example, including the current directory in the LD_LIBRARY_PATH would enable it to find the .so files in the current directory:

export LD_LIBRARY_PATH=./:$LD_LIBRARY_PATH

sometimes I needed to run `sudo ldconfig` to get some installed files to be recognized, but I don't think that is the case here.

**Comment by rcoreilly** [comment] 2020-10-27 00:13
I have a tiny bit of progress on this -- just trying the basic `hi` example on my mac in response to #234 -- got link errors using the `gopy build` command, but then went into `out` directory and tried the `make` command, which worked!  This shows where at least one problem is, for my setup, which may or may not apply to other cases above.  Dealing with all this path stuff is a great reminder of how awesome Go is for not having any of these issues itself!

So, the first point is: if you have any problems, try going into the output directory and running `make`

Here's the command that gopy build runs, which reliably produces link errors when I run it manually in the out directory:
```sh
clang hi.c -dynamiclib hi_go.so -o _hi.so -I/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/include/python3.8 -I/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/include/python3.8 -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -L/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/config-3.8-darwin -ldl -framework CoreFoundation -fPIC --shared -Ofast
```

And here's the version based on the Makefile that works:

```sh
clang hi.c -dynamiclib hi_go.so -o _hi.so -I/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/include/python3.8 -I/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/include/python3.8 -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -L/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib -lpython3.8 -ldl -framework CoreFoundation -fPIC --shared -Ofast
```

The key diff is this:
```sh
LDFLAGS = -L/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib -lpython3.8 -ldl   -framework CoreFoundation 
```

so somehow the Makefile generator is coming up with a working version of LDFLAGS whereas the go build version is not correct.  I will investigate later but just leaving breadcrumbs here.

**Comment by rcoreilly** [comment] 2020-10-27 10:40
I just pushed a version that fixes my build on mac, by using the LDFLAGS from the bind code -- hopefully that fixes these issues?  Anyone still here to test it?  Anyway, I will test on linux soon too.

**Comment by rcoreilly** [comment] 2021-09-01 06:08
assuming this is now fixed..

**Closed by rcoreilly** 2021-09-01 06:08 UTC
