### ISSUE TITLE
Best way to pass data chunks (bytes, bytearray)?

### ISSUE THREAD

**Issue by morgenroth** [go-python/gopy#328] opened 2023-05-02 15:18 UTC
What is the best way to pass (python -> go) and retrieve (python <- go) data chunks?

I have tried to create a simple interface as shown below, but this does not compile into a working interface.

```golang
func DataWrite(handle int, buf []byte) int {
...
}

func DataRead(handle int, buf []byte) int {
...
}
```

gopy seems to handle `[]byte` as kind of object and then `.handle` is missing.
```
AttributeError: 'bytes' object has no attribute 'handle'
```

Then I tried to go with the Slice approach but aside from the drawback mentioned in #323, I have not found any way to actually put data into the arrays.

Can somebody provide or point me to a working example (go and python code) which shows how arrays of bytes can be efficiently passed with gopy? Thanks!

**Comment by rcoreilly** [comment] 2023-05-08 17:06
This is really a dupe of #323.  don't explicitly create the handle -- gopy manages all that.  slices example should be sufficient, also see the python wrapper to see exactly what that looks like.

**Closed by rcoreilly** 2023-05-08 17:06 UTC
